CoreOffice/CoreXLSX

.gitignore, .travis.yml, CoreXLSX.xcodeproj/CoreXLSXTests_Info.plist, CoreXLSX.xcodeproj/CoreXLSX_Info.plist, CoreXLSX.xcodeproj/XMLCoder_Info.plist, CoreXLSX.xcodeproj/XMLParsing_Info.plist, CoreXLSX.xcodeproj/ZIPFoundation_Info.plist, CoreXLSX.xcodeproj/project.pbxproj, CoreXLSX.xcodeproj/project.xcworkspace/contents.xcworkspacedata, CoreXLSX.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, CoreXLSX.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, CoreXLSX.xcodeproj/xcshareddata/xcschemes/CoreXLSX-Package.xcscheme, Package.resolved, Package.xcconfig, Sources/CoreXLSX/CoreXLSX.swift, Sources/CoreXLSX/Worksheet.swift, Tests/CoreXLSXTests/CoreXLSXTests.swift, _Pods.xcodeproj
This new API allows users to filter all cells by a row or column reference. To avoid re-parsing of worksheets, a new private `worksheetCache` property is added on `XLSXFile`.
=> Cell by row/column filtering API with worksheetCache

CoreXLSX.xcodeproj/project.pbxproj, Sources/CoreXLSX/Worksheet.swift
Some properties on `Worksheet` and its descendants had obscure names, most of that is fixed now with old names marked as deprecated.
=> Improve Worksheet model property naming

.travis.yml, CoreXLSX.xcodeproj/project.pbxproj, Sources/CoreXLSX/CellReference.swift, Sources/CoreXLSX/ColumnReference.swift, Sources/CoreXLSX/CoreXLSX.swift, Sources/CoreXLSX/Relationships.swift, Sources/CoreXLSX/Worksheet.swift, Tests/CoreXLSXTests/CellReferenceTests.swift, Tests/CoreXLSXTests/CoreXLSXTests.swift, Tests/CoreXLSXTests/RelationshipsTests.swift, Tests/CoreXLSXTests/XCTestManifests.swift, codecov.yml
Previously cell references were stringly-typed allowing a user to create a cell reference with an arbitrary string. This is fixed with an introduction of new types: `CellReference` and `ColumnReference`. `ColumnReference` is a simple wrapper around `String` that guards against empty string and characters that can't be used as column references. Rows don't need a separate type for references as they map neatly to `UInt`, although API parts that used row references have changed to use `UInt` instead of `Int`. This is a breaking change that requires a major version bump.
=> Add ColumnReference type with new API

CoreXLSX.xcodeproj/xcshareddata/xcbaselines/CoreXLSX::CoreXLSXTests.xcbaseline/D6D73CD6-7630-483B-93EE-17F5BBBE89AF.plist, CoreXLSX.xcodeproj/xcshareddata/xcbaselines/CoreXLSX::CoreXLSXTests.xcbaseline/Info.plist, Sources/CoreXLSX/ColumnReference.swift, Sources/CoreXLSX/Worksheet.swift, Tests/CoreXLSXTests/CellReferenceTests.swift, Tests/CoreXLSXTests/CoreXLSXTests.swift
Currently `ColumnReference` lacks `Strideable` implementation, which does not allow closed ranges on column references like `ColumnReference("A")...ColumnReference("CZ")`. This prevents efficient filtering of cells with closed ranges requiring users to specify every column explicitly in arrays or whatever collection other than `ClosedRange`. Adding `Strideable` implementation with unit and performance tests here.
=> Implement Strideable on ColumnReference

.gitignore, .travis.yml, Cartfile, Cartfile.resolved, CoreXLSX.podspec, CoreXLSX.xcodeproj/CoreXLSXiOS_Info.plist, CoreXLSX.xcodeproj/CoreXLSXtvOS_Info.plist, CoreXLSX.xcodeproj/CoreXLSXwatchOS_Info.plist, CoreXLSX.xcodeproj/project.pbxproj, CoreXLSX.xcodeproj/xcshareddata/xcschemes/CoreXLSXiOS.xcscheme, CoreXLSX.xcodeproj/xcshareddata/xcschemes/CoreXLSXmacOS.xcscheme, CoreXLSX.xcodeproj/xcshareddata/xcschemes/CoreXLSXtvOS.xcscheme, CoreXLSX.xcodeproj/xcshareddata/xcschemes/CoreXLSXwatchOS.xcscheme, Package.swift, README.md
By default Carthage tries to build for all platforms marked as "supported" in the Xcode project, so this was a good excuse to add that the podspec as well. Carthage support was fixed by adding a per-platform target in the Xcode project and linking correct dependencies for every platform in settings of each target.
Resolves #4.
=> Add Carthage and support for tvOS and watchOS

.travis.yml, CoreXLSX.xcodeproj/project.pbxproj, Sources/CoreXLSX/Worksheet.swift, Tests/CoreXLSXTests/CoreXLSXTests.swift
There are APIs to filter cells by rows and columns separately, but no API for filtering by both criteria at the same time. This is added with an implementation similar to those previous APIs with new assertions in tests.
=> Add API for filtering cells by rows and columns

Example/CoreXLSX.xcodeproj/project.pbxproj, Tests/CoreXLSXTests/XCTestManifests.swift
Example project has a separate project file, which wasn't updated after new files were added to the main CoreXLSX module.
=> Fix example project after new files were added

Sources/CoreXLSX/Worksheet.swift
As reported in #12, there are worksheets that apparently don't have `cols` node, which means that `columns` property on `Worksheet` should be optional.
=> Make `columns` property optional on `Worksheet`

Sources/CoreXLSX/CoreXLSX.swift, Sources/CoreXLSX/Worksheet.swift, Tests/CoreXLSXTests/CoreXLSXTests.swift
As previously reported, there are Excel documents in the wild that contain no `sheetData` node. While I was no able to recreate these sheets, I assume these still can be generated by some tools or apps. They do make sense as empty worksheets, so let's allow these in the `Worksheet` model type. To cleanup the naming a new non-optional property `data` has been added. The previous name and type are aliased for source compatibility with a deprecation warning.
Resolves #15
=> Rename sheetData on Worksheet and make it optional

CoreXLSX.xcodeproj/project.pbxproj, Sources/CoreXLSX/CoreXLSX.swift, Sources/CoreXLSX/Relationships.swift, Sources/CoreXLSX/SharedStrings.swift, Sources/CoreXLSX/Worksheet/Worksheet.swift, Tests/CoreXLSXTests/CellReference.swift, Tests/CoreXLSXTests/CoreXLSX.swift, Tests/CoreXLSXTests/CoreXLSXTests.swift, Tests/CoreXLSXTests/Relationships.swift, Tests/CoreXLSXTests/SharedStrings.swift, Tests/CoreXLSXTests/Workbook.swift, Tests/CoreXLSXTests/Worksheet.swift
As reported in #21, there's no obvious way to get values for some values. That's caused by the fact that some of the values are stored in a separate file, which is usually located at the path `sharedStrings.xml`. This can be parsed to a corresponding model type and then processed by users of `CoreXLSX` to get the string values.
=> Add SharedStrings model, parse sharedStrings.xml

Sources/CoreXLSX/CoreXLSX.swift, Sources/CoreXLSX/Relationships.swift, Tests/CoreXLSXTests/Relationships.swift
As reported in #19 without a `public Relationships` type `Workbook` values can't be matched to `Worksheet` cleanly. `Relationships` type already existed in the library, so it makes sense to make it `public` and to expose `public func parseRelationships` that returns a value of that type for a given `XLSXFile` instance.
Resolves #19.
=> Make Relationships public, add parseRelationships

Sources/CoreXLSX/CoreXLSX.swift
A followup to #19: `XLSXFile.parseRelationships` returns only a parsed root `_rels/.rels` file, but there's no public API to get relationships for every document parsed from the root relationships file. `parseDocumentRelationships` implements that.
=> Add `public func parseDocumentRelationships`

Sources/CoreXLSX/CoreXLSX.swift
Add parameter to init function with default value 10mb.
Resolves #26 #27
=> Add bufferSize parameter to init

Sources/CoreXLSX/Worksheet/Cell.swift, Sources/CoreXLSX/Worksheet/Worksheet.swift, Tests/CoreXLSXTests/CoreXLSX.swift
=> Refactor Worksheet and Pane values to optional

.travis.yml, Sources/CoreXLSX/Relationships.swift
dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "relationship", intValue: nil), _XMLKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "type", intValue: nil)], debugDescription: "Cannot initialize SchemaType from invalid String value http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties", underlyingError: nil))
=> Add `customProperties` relationship

Sources/CoreXLSX/CoreXLSX.swift
New version of `XMLCoder` exposes `errorContextLength`, which could greatly help with diagnostics. There's now an additional argument with a default value of `0` exposed on `XLSXFile` initializer.
Resolves #32
=> Expose `errorContextLength` on `struct XLSXFile`

.swiftlint.yml, .travis.yml, CoreXLSX.xcodeproj/project.pbxproj, Example/CoreXLSX.xcodeproj/project.pbxproj, Example/CoreXLSXExample/AppDelegate.swift, Example/CoreXLSXExample/ViewController.swift, Example/Podfile.lock, Package.swift, Sources/CoreXLSX/CoreXLSX.swift, Sources/CoreXLSX/Path.swift, Sources/CoreXLSX/Relationships.swift, Sources/CoreXLSX/Workbook.swift, Sources/CoreXLSX/Worksheet/Cell.swift, Sources/CoreXLSX/Worksheet/CellQueries.swift, Sources/CoreXLSX/Worksheet/CellReference.swift, Sources/CoreXLSX/Worksheet/ColumnReference.swift, Sources/CoreXLSX/Worksheet/Worksheet.swift, Tests/CoreXLSXTests/CellReference.swift, Tests/CoreXLSXTests/CoreXLSX.swift, Tests/CoreXLSXTests/Relationships.swift, Tests/CoreXLSXTests/SharedStrings.swift, Tests/CoreXLSXTests/Workbook.swift, Tests/CoreXLSXTests/Worksheet.swift
This fixes some of the errors thrown by the file attached in #41. Support for XML namespaces which that file uses for worksheet data will be resolved in a separate PR.
=> Fix root paths in CoreXLSX, fix formatter & linter

README.md, Tests/CoreXLSXTests/SharedStrings.swift
=> Add test to check sharedStrings order

.travis.yml, Tests/CoreXLSXTests/CoreXLSX.swift, Tests/CoreXLSXTests/SharedStrings.swift
=> Add testSpacePreserve to SharedStrings tests

Sources/CoreXLSX/SharedStrings.swift, Tests/CoreXLSXTests/SharedStrings.swift
There should be a `<t>` tag when format is applied at the character level; Follow the [reference](https://docs.microsoft.com/en-us/office/open-xml/working-with-the-shared-string-table)
=> missing `text` property when format is applied at the character level

CoreXLSX.xcodeproj/project.pbxproj, test_swiftpm.sh, test_xcodebuild.sh
All of these targets are failing due to `Comments.swift` file not added to all targets. CI still passes though as `pipefail` isn't applied to all script commands.
=> Fix non-macOS framework targets

Cartfile, Cartfile.resolved, CoreXLSX.podspec, Example/Podfile.lock, Package.resolved, Package.swift, Package@swift-4.2.swift
Looks like 404 checks reported by `pod lib lint` are triggered by `social_media_url` in the podspec, this is now removed to make the checks pass.
=> Bump XMLCoder dependency to 0.8.0

.swiftlint.yml, pod.sh
Also, work around CocoaPods CI job issues.
=> Bump line length limit in .swiftlint.yml

Cartfile, Cartfile.resolved, CoreXLSX.podspec, Example/Podfile.lock, Package.resolved, Package.swift, Package@swift-4.2.swift
Notable updates in the new version:
>   * Fixed a race condition during archive creation or extraction
>   * Fixed an error when trying to add broken symlinks to an archive
>   * Fixed an App Store submission issue by updating the product identifier to use reverse DNS notation
>   * Improved CRC32 calculation performance
>   * Improved entry replacement performance on separate volumes
>   * Improved documentation for closure-based writing
=> Update ZIPFoundation to 0.9.10

Sources/CoreXLSX/Workbook.swift, Tests/CoreXLSXTests/CellReference.swift, Tests/CoreXLSXTests/CoreXLSX.swift, Tests/CoreXLSXTests/Formula.swift, Tests/CoreXLSXTests/Namespaces.swift, Tests/CoreXLSXTests/Relationships.swift, Tests/CoreXLSXTests/Workbook.swift, Tests/CoreXLSXTests/XCTestManifests.swift
Fix reported test case, regenerate Linux tests, make tests more friendly towards parallel runs by avoiding sharing decoder instances.
=> Fix workbooks with no views, cleanup tests

Sources/CoreXLSX/Relationships.swift
http://schemas.openxmlformats.org/officeDocument/2006/relationships/\
metadata/core-properties
in Relationships.swift officeDocument was written lowercase which caused a crash when reading file.parseWorksheetPaths()
=> officeDocument is misspelled in corePropreties Relationship

Sources/CoreXLSX/XLSXFile.swift, Tests/CoreXLSXTests/Workbook.swift, Tests/CoreXLSXTests/XCTestManifests.swift
=> Add func parseWorksheetPathsAndNames on XLSXFile

.vscode/settings.json, .vscode/tasks.json, LICENSE.md, Sources/CoreXLSX/Comments.swift, Sources/CoreXLSX/Path.swift, Sources/CoreXLSX/Relationships.swift, Sources/CoreXLSX/SharedStrings.swift, Sources/CoreXLSX/Styles.swift, Sources/CoreXLSX/Workbook.swift, Sources/CoreXLSX/Worksheet/Cell.swift, Sources/CoreXLSX/Worksheet/CellQueries.swift, Sources/CoreXLSX/Worksheet/CellReference.swift, Sources/CoreXLSX/Worksheet/ColumnReference.swift, Sources/CoreXLSX/Worksheet/Worksheet.swift, Sources/CoreXLSX/XLSXFile.swift, Tests/CoreXLSXTests/Border.swift, Tests/CoreXLSXTests/CellReference.swift, Tests/CoreXLSXTests/Comments.swift, Tests/CoreXLSXTests/Formula.swift, Tests/CoreXLSXTests/Namespaces.swift, Tests/CoreXLSXTests/Relationships.swift, Tests/CoreXLSXTests/SharedStrings.swift, Tests/CoreXLSXTests/Styles.swift, Tests/CoreXLSXTests/Workbook.swift, Tests/CoreXLSXTests/Worksheet.swift
With the new `Data` initializer on `XLSXFile` the `filepath` property no longer makes sense. It also wasn't used anywhere internally.
=> Add data XLSXFile.init, remove filepath property

CoreXLSX.xcodeproj/project.pbxproj, Sources/CoreXLSX/Worksheet/Cell.swift, Sources/CoreXLSX/Worksheet/CellQueries.swift, Tests/CoreXLSXTests/CellQueries.swift, Tests/CoreXLSXTests/Comments.swift, Tests/CoreXLSXTests/SharedStrings.swift, Tests/CoreXLSXTests/Styles.swift
=> Fix time values returned by Cell.dateValue

Sources/CoreXLSX/Worksheet/Worksheet.swift
Attempt to fix some of the issues reported in #94.
=> Make count optional in MergeCells

Sources/CoreXLSX/Relationships.swift, Tests/CoreXLSXTests/Relationships.swift
I tried to parse a spreadsheet, it failed with:
```
Cannot initialize SchemaType from invalid String value http://schemas.microsoft.com/office/2017/10/relationships/person
```
I added the case and it fixed my issue locally.
I added a test. I will change it up however you want, but I can't include the original spreadsheet, sorry.
=> Add “person” to the relationship types

CoreXLSX.xcodeproj/project.pbxproj, README.md, Sources/CoreXLSX/Worksheet/Cell.swift, Sources/CoreXLSX/Worksheet/CellQueries.swift, Sources/CoreXLSX/XLSXFile.swift, Tests/CoreXLSXTests/CellQueries.swift, Tests/CoreXLSXTests/CellReference.swift, Tests/CoreXLSXTests/Styles.swift, Tests/CoreXLSXTests/XLSXFile.swift, azure-pipelines.yml
=> Add `font(in:)` and `format(in:)` functions

Sources/CoreXLSX/Worksheet/ColumnReference.swift, Tests/CoreXLSXTests/CellReference.swift, Tests/CoreXLSXTests/XCTestManifests.swift
=> Compare `ColumnReference` by `intValue`
